### PR TITLE
Keyboard event fixes

### LINKED ISSUE #6: Accuracy of `KeyModes` name
Hate to spoil it, но "**Key**board **mod**ification" сокращается не до "KeyMode", а до "KeyMod", т.к. "Mode" — это режим, а "Mod" — это сокращение от "Modification" (в переводе "изменение", т.к. эта битовая маска изменяет нажатую клавишу). Предложение заключается в переименовании этого поля, пока оно ещё не в стандарте.
edfb5616761ef7c81bcf060c19ad1e456de40f81

### PR DESCRIPTION
**Pull request by quadratic-bit**
`KeyEvent`'s mod should be explicitly presented as a bitmask. Also fixes #6.

### CODE REVIEW

File: include/dr4/event.hpp [hunk 1]
```diff
@@ -36,8 +36,8 @@ struct Event {
     };
 
     struct KeyEvent {
-        dr4::KeySyms sym;
-        dr4::KeyModes mod;
+        dr4::KeySym sym;
+        uint16_t mods;
```
Comment (I1Va) [inline include/dr4/event.hpp]: Мб лучше dr4::KeyMode оставить?

**Review by I1Va — APPROVED** [review]
